# Documentation for Soundcloud playlist album specfiles.
# Below you will find an unmodified, but commented specfile obtained by fetching:
# `https://soundcloud.com/alcomindz/sets/koldi-kolins-dawaj-mixtape-2018`

# Playlist albums start with the `playlist` table.
[playlist]
# This id can be changed - it is used for naming directories and logging. In other words it is for you to change.
id = "877644385"
# The title of the album - used for tagging and as the name of the output directory for tagged files.
# Do not worry about making it path safe, the program will sanitise the path if necessary (not yet implemented).
title = "Koldi & Kolins - Dawaj! Mixtape (2018)"
# The release year of the album. It is not used when the output format is `mp3` because ID3 is annoying with dates
# and it does not display them in music players anyway (maybe a library issue or the music player's).
# It is only the year in four digit format, e.g `2015`. Passing anything more will just truncate it to four digits:
# `2019-10-23` becomes `2019`.
release_year = ""
# Album artists is an array (vector) of strings with names. These strings will be concatenated using commas.
# For albums from Soundcloud this filled will be automatically filled, but will usually be wrong.
album_artists = ["Alcomindz"]
# Genre of the album. DO NOT pass an ID3 genre id - the program does not make any attempt to resolve that.
# The unmodified string literal is set as the genre field.
genre = ""
# The total number of tracks in the album. One could think it is useless, BUT some albums might be missing tracks due
# to time passing or copyright stuff. Adjust this if necessary and remember to correct track numbers too.
track_total = 6
# The front cover URL, may be the `file` or `http`(`s`) scheme. If it is a file it will be read from the local
# filesystem. In the other cases it will be fetched from the Internet.
# Examples:
# - a file `cover = "file:///home/user/Downloads/dawaj.png"`
# - a network location `cover = "https://i1.sndcdn.com/artworks-000603114193-lwxs8d-t500x500.jpg"`
cover = "https://i1.sndcdn.com/artworks-000603114193-lwxs8d-t500x500.jpg"

# Here comes a list of tracks. Each track is the same, so only one will be documented.
[[track]]
# The url of the track automatically obtained from fetching. Any single Soundcloud track can be passed here, 
# but has to be in the format below. You can also pass a single video YouTube URL in case a track is missing from
# Soundcloud (just create a new `track` entry). Files are also supported if you magically own a copy of the missing track.
# For how to specify local file URLs look at `album.cover`.
url = "https://api-v2.soundcloud.com/tracks/686601196"
# The title used for tagging and as a resulting file name of the tagged file.
# The file name of the tagged file will be `<track_num>. <title>` with `track_num` padded to two digits.
title = "Dawaj!"
# Contributing artists as an array of strings. These strings will be concatenated using commas.
# It is planned to make this field optional, in the case it's not present the `chapters.album_artists` field
# will be used. For albums fetched from Soundcloud this field will be filled automatically, but might be wrong,
# like in this case two artists are in the same string.
artists = ["Koldi & Kolins"]
# The track number. If you add an entry with a foreign URL remember to correct this field in the other tracks.
# This field can also be used to reorder tracks if necessary.
track_num = 1

[[track]]
url = "https://api-v2.soundcloud.com/tracks/686601160"
title = "Parę Browarków"
artists = ["Koldi & Kolins"]
track_num = 2

[[track]]
url = "https://api-v2.soundcloud.com/tracks/686601121"
title = "Dziewczyno 4 (feat. Fifson)"
artists = ["Koldi & Kolins"]
track_num = 3

[[track]]
url = "https://api-v2.soundcloud.com/tracks/686601067"
title = "Czarodziej Baba (prod. Oil Beatz)"
artists = ["Koldi & Kolins"]
track_num = 4

[[track]]
url = "https://api-v2.soundcloud.com/tracks/686601022"
title = "MTMG (feat. Raxxity)"
artists = ["Koldi & Kolins"]
track_num = 5

[[track]]
url = "https://api-v2.soundcloud.com/tracks/686601007"
title = "Neymar Remix"
artists = ["Koldi & Kolins"]
track_num = 6
